# Generated by Django 5.2 on 2025-04-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_tag_community_tags'),
        ('posts', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='communities.tag'),
        ),
    ]
