# Generated by Django 5.2 on 2025-05-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_tag_community_tags'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='communities.tag'),
        ),
    ]
